export const config = {
  port: Number(process.env.PORT || 3001),
  host: process.env.HOST || '127.0.0.1',
  jwtSecret: process.env.JWT_SECRET || 'aakashik-dev-secret-change-in-production',
  adminEmail: process.env.ADMIN_EMAIL || 'owner@aakashik.local',
  adminPassword: process.env.ADMIN_PASSWORD || 'Admin@1234',
  dbPath: process.env.DB_PATH || 'data/aakashik.db',
  isTest: process.env.NODE_ENV === 'test',
  frontendUrl: process.env.FRONTEND_URL || 'http://127.0.0.1:8080',
  googleClientId: process.env.GOOGLE_CLIENT_ID || '',
  googleClientSecret: process.env.GOOGLE_CLIENT_SECRET || '',
  googleRedirectUri: process.env.GOOGLE_REDIRECT_URI || 'http://127.0.0.1:3001/api/auth/google/callback',
  cookieDomain: process.env.COOKIE_DOMAIN || '',
  cookieSecure: process.env.COOKIE_SECURE === 'true' || process.env.NODE_ENV === 'production',
  sessionCookieName: 'ak_session',
  oauthStateCookieName: 'ak_oauth_state',
  smtpHost: process.env.SMTP_HOST || '',
  smtpPort: Number(process.env.SMTP_PORT || 465),
  smtpSecure: process.env.SMTP_SECURE !== 'false',
  smtpUser: process.env.SMTP_USER || '',
  smtpPass: process.env.SMTP_PASS || '',
  smtpFrom: process.env.SMTP_FROM || 'Aakashik Wellness <care@aakashikwellness.in>',
};
